Upload to PyPI with twine
The old method fails:
```
Submitting dist/pylast-1.7.0.tar.gz to https://upload.pypi.org/legacy/
Upload failed (403): Invalid or non-existent authentication information.
error: Upload failed (403): Invalid or non-existent authentication information.
```
Also don't need to register with twine, despite what its docs say.
[CI skip]